### ISSUE TITLE
Could not find the proper steps to setup this repository.

### ISSUE THREAD

**Issue by Pratyush2586** [MarketSquare/robotframework-ai#13]
I'm evaluating the capabilities of GENAI in the Robot Framework. Could you provide the steps to set up the repository and an example of how to use the code for generating test data?

**Comment by xfoggi** [comment]
Hi @Pratyush2586, what is missing for you in the current readme file to run the library? We are looking to extend our documentation, but it would help us know what exactly is missing. Thanks!

**Comment by StijnDeJong** [comment]
Hello Pratyush, we haven't heard from you in a while so we assume your issue has been fixed. If you are stilling experiencing problems, please create a new issue.
