### ISSUE TITLE
Module not found issues are observed for python files within robot test scripts.

### ISSUE THREAD

**Issue by gnu1207** [MarketSquare/robotframework-ai#15]
I am using this repository in Pycharm, and python Library used in robot file always says module not found.
Tried with setting up the PYTHONPATH, by providing full path of the file, but no luck.

**Comment by StijnDeJong** [comment]
Hello gnu,

I have updated the README.md and added a Setup section, can you take a look at that.
Hope this helps!

**Comment by StijnDeJong** [comment]
Hello gnu, we haven't heard from you in a while so we assume your issue has been fixed. If you are stilling experiencing problems please create a new issue.
